---
- name: Run pipeline
  hosts: localhost
  tasks:

    - name: Cleanup repository directory
      file:
        path: "{{ repo_dir }}"
        state: absent
      vars:
        repo_dir: "class"

    - name: Stop and remove existing Docker container
      shell: |
        if [ $(docker ps -a -q -f name={{ container_name }}) ]; then
          docker stop {{ container_name }} || true
          docker rm {{ container_name }} || true
        fi
      vars:
        container_name: "my_nginx_container"

    - name: Clone the repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ repo_dir }}"
      vars:
        repo_url: "https://github.com/nafrinmeir/class.git"
        repo_dir: "class"

    - name: Build Docker image
      command: docker build -t {{ docker_image }}:{{ docker_tag }} .
      args:
        chdir: "{{ repo_dir }}"
      vars:
        docker_image: "nginx"
        docker_tag: "latest"

    - name: Stop any process using port 8082
      shell: |
        if [ $(lsof -t -i:8082) ]; then
          kill -9 $(lsof -t -i:8082) || true
        fi

    - name: Run Docker container
      command: docker run -d --name {{ container_name }} -p 8082:80 {{ docker_image }}:{{ docker_tag }}
      vars:
        container_name: "my_nginx_container"
        docker_image: "nginx"
        docker_tag: "latest"

    - name: Cleanup workspace
      file:
        path: "{{ repo_dir }}"
        state: absent
      vars:
        repo_dir: "class"
